### ISSUE TITLE
Use skip_testing to speed up scan

### ISSUE THREAD

**Issue by dyang** [lyndsey-ferguson/setup_fragile_tests_for_rescan#1]
Is it possible to use the `skip_testing` option in scan to avoid re-building after each rescan? 

I'm thinking that instead of "patching up" xcodeproj for the next run, one can potentially run scan with the `skip_testing` +` test_without_building` options. Depending on the time it takes to build, this could significantly speed things up.

Does this make sense?

**Comment by dyang** [comment]
Just took a closer at your source code and discovered that `:passed_tests` and `:failed_tests` are already supported as return values.  Good job! :)

Do you think it makes sense to make the "patching up" xcodeproj bit optional now that there's no need to rebuild across test runs? In that case `report_filepath` is the only mandatory argument.

**Comment by lyndsey-ferguson** [comment]
@dyang you should checkout the actions in my new fastlane plugin, `test_center`. This pretty much will replace `setup_fragile_tests_for_rescan` and give you what you're looking for. 

It has actions to get the tests from the junit report and to re-run the failing tests.
