### ISSUE TITLE
Unable to run failed tests

### ISSUE THREAD

**Issue by mishrav** [lyndsey-ferguson/setup_fragile_tests_for_rescan#2]
[09:39:07]: Exit status: 65
+--------------------+---+
|      Test Results      |
+--------------------+---+
| Number of tests    | 7 |
| Number of failures | 1 |
+--------------------+---+

[09:39:08]: failure noted: Tests have failed
[09:39:08]: --------------------------------------------
[09:39:08]: --- Step: setup_fragile_tests_for_rescan ---
[09:39:08]: --------------------------------------------
+----------------------------+-------------------------------------+
|                           Lane Context                           |
+----------------------------+-------------------------------------+
| PLATFORM_NAME              |                                     |
| LANE_NAME                  | featuretest                         |
| SCAN_DERIVED_DATA_PATH     | /Users/myusername/Library/Develo  |
|                            | per/Xcode/DerivedData/myAppHori  |
|                            | zontal-feecdbysbgyjfzdeythwumcpsam  |
|                            | z                                   |
| SCAN_GENERATED_PLIST_FILES | ["/Users/myusername/Library/Deve  |
|                            | loper/Xcode/DerivedData/myAppHo  |
|                            | rizontal-feecdbysbgyjfzdeythwumcps  |
|                            | amz/Logs/Test/A2F4CF43-D08E-4BBF-A  |
|                            | 3D3-8B4A49062FEA_TestSummaries.pli  |
|                            | st"]                                |
| SCAN_GENERATED_PLIST_FILE  | /Users/myusername/Library/Develo  |
|                            | per/Xcode/DerivedData/myAppHori  |
|                            | zontal-feecdbysbgyjfzdeythwumcpsam  |
|                            | z/Logs/Test/A2F4CF43-D08E-4BBF-A3D  |
|                            | 3-8B4A49062FEA_TestSummaries.plist  |
+----------------------------+-------------------------------------+
[09:39:10]: Missing end tag for 'unknown' (got "section")
Line: -1
Position: -1
Last 80 unconsumed characters:

+------+------------------------+-------------+
|              fastlane summary               |
+------+------------------------+-------------+
| Step | Action                 | Time (in s) |
+------+------------------------+-------------+
| 💥   | scan                   | 360         |
| 💥   | setup_fragile_tests_f  | 0           |
|      | or_rescan              |             |
+------+------------------------+-------------+

+------------+--------------+----------------+
|          Plugin updates available          |
+------------+--------------+----------------+
| Plugin     | Your Version | Latest Version |
+------------+--------------+----------------+
| bluepillar | 0.2.0        | 0.3.0          |
+------------+--------------+----------------+
[09:39:10]: To update all plugins, just run
[09:39:10]: $ fastlane update_plugins

[09:39:10]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️  Fix for _options
    https://github.com/fastlane/fastlane/pull/80 [closed] 0 💬
    04 Feb 2017

🔗  You can ⌘ + double-click on links to open them directly in your browser.
/Users/myusername/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/rexml/parsers/baseparser.rb:341:in **`pull_event': [!] Missing end tag for 'unknown' (got "section") (REXML::ParseException)
Line: -1
Position: -1
Last 80 unconsumed characters:

Line: -1
Position: -1
Last 80 unconsumed characters:**
	from /Users/myusername/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/rexml/parsers/baseparser.rb:185:in `pull'
	from /Users/myusername/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/rexml/parsers/treeparser.rb:23:in `parse'
	from /Users/myusername/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/rexml/document.rb:288:in `build'
	from /Users/myusername/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/rexml/document.rb:45:in `initialize'
	from /Users/myusername/.rvm/gems/ruby-2.4.0/gems/fastlane-plugin-setup_fragile_tests_for_rescan-1.1.0/lib/fastlane/plugin/setup_fragile_tests_for_rescan/actions/setup_fragile_tests_for_rescan_action.rb:10:in `new'
	from /Users/myusername/.rvm/gems/ruby-2.4.0/gems/fastlane-plugin-setup_fragile_tests_for_rescan-1.1.0/lib/fastlane/plugin/setup_fragile_tests_for_rescan/actions/setup_fragile_tests_for_rescan_action.rb:10:in `block in run'
	from /Users/myusername/.rvm/gems/ruby-2.4.0/gems/fastlane-plugin-setup_fragile_tests_for_rescan-1.1.0/lib/fastlane/plugin/setup_fragile_tests_for_rescan/actions/setup_fragile_tests_for_rescan_action.rb:10:in `open'
	from /Users/myusername/.rvm/gems/ruby-2.4.0/gems/fastlane-plugin-setup_fragile_tests_for_rescan-1.1.0/lib/fastlane/plugin/setup_fragile_tests_for_rescan/actions/setup_fragile_tests_for_rescan_action.rb:10:in `run'
	from /Users/myusername/.rvm/gems/ruby-2.4.0@global/gems/fastlane-2.37.0/fastlane/lib/fastlane/runner.rb:252:in `block (2 levels) in execute_action'
	from /Users/myusername/.rvm/gems/ruby-2.4.0@global/gems/fastlane-2.37.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Users/myusername/.rvm/gems/ruby-2.4.0@global/gems/fastlane-2.37.0/fastlane/lib/fastlane/runner.rb:230:in `block in execute_action'
	from /Users/myusername/.rvm/gems/ruby-2.4.0@global/gems/fastlane-2.37.0/fastlane/lib/fastlane/runner.rb:226:in `chdir'
	from /Users/myusername/.rvm/gems/ruby-2.4.0@global/gems/fastlane-2.37.0/fastlane/lib/fastlane/runner.rb:226:in `execute_action'
	from /Users/myusername/.rvm/gems/ruby-2.4.0@global/gems/fastlane-2.37.0/fastlane/lib/fastlane/runner.rb:148:in `trigger_action_by_name'
	from /Users/myusername/.rvm/gems/ruby-2.4.0@global/gems/fastlane-2.37.0/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
	from ../fastlane/Fastfile:20:in `rescue in block in parsing_binding'
	from ../fastlane/Fastfile:10:in `block in parsing_binding'
	from /Users/myusername/.rvm/gems/ruby-2.4.0@global/gems/fastlane-2.37.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/myusername/.rvm/gems/ruby-2.4.0@global/gems/fastlane-2.37.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/myusername/.rvm/gems/ruby-2.4.0@global/gems/fastlane-2.37.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/myusername/.rvm/gems/ruby-2.4.0@global/gems/fastlane-2.37.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/myusername/.rvm/gems/ruby-2.4.0@global/gems/fastlane-2.37.0/fastlane/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
	from /Users/myusername/.rvm/gems/ruby-2.4.0@global/gems/fastlane-2.37.0/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Users/myusername/.rvm/gems/ruby-2.4.0@global/gems/fastlane-2.37.0/fastlane/lib/fastlane/commands_generator.rb:104:in `block (2 levels) in run'
	from /Users/myusername/.rvm/gems/ruby-2.4.0@global/gems/commander-fastlane-4.4.4/lib/commander/command.rb:178:in `call'
	from /Users/myusername/.rvm/gems/ruby-2.4.0@global/gems/commander-fastlane-4.4.4/lib/commander/command.rb:153:in `run'
	from /Users/myusername/.rvm/gems/ruby-2.4.0@global/gems/commander-fastlane-4.4.4/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/myusername/.rvm/gems/ruby-2.4.0@global/gems/fastlane-2.37.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:39:in `run!'
	from /Users/myusername/.rvm/gems/ruby-2.4.0@global/gems/commander-fastlane-4.4.4/lib/commander/delegates.rb:15:in `run!'
	from /Users/myusername/.rvm/gems/ruby-2.4.0@global/gems/fastlane-2.37.0/fastlane/lib/fastlane/commands_generator.rb:303:in `run'
	from /Users/myusername/.rvm/gems/ruby-2.4.0@global/gems/fastlane-2.37.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /Users/myusername/.rvm/gems/ruby-2.4.0@global/gems/fastlane-2.37.0/fastlane/lib/fastlane/cli_tools_distributor.rb:66:in `take_off'
	from /Users/myusername/.rvm/gems/ruby-2.4.0@global/gems/fastlane-2.37.0/bin/fastlane:20:in `<top (required)>'
	from /Users/myusername/.rvm/rubies/ruby-2.4.0/bin/fastlane:22:in `load'
	from /Users/myusername/.rvm/rubies/ruby-2.4.0/bin/fastlane:22:in `<main>'
	from /Users/myusername/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `eval'
	from /Users/myusername/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `<main>'

**Comment by lyndsey-ferguson** [comment]
Looks like it had a problem parsing the xml report file. Can you post it so I can look into the problem?

**Comment by lyndsey-ferguson** [comment]
@mishrav is your problem resolved? Let me know.

**Comment by lyndsey-ferguson** [comment]
Closing the issue after no update.
