### ISSUE TITLE
Rerunning tests compiles app each time

### ISSUE THREAD

**Issue by ericwengelking** [lyndsey-ferguson/setup_fragile_tests_for_rescan#4]
It would save a lot of time if the source was only compiled before the first run of the tests.  This should be possible with xcodebuild parameter `test-without-building`

**Comment by WesleyJacobsMP** [comment]
Have you found a way to integrate this? Cause it would help me a lot as well

**Comment by lyndsey-ferguson** [comment]
Sorry everyone, I just saw these messages. I wanted to keep this action as simple as possible. I too build before running using the `gym` action from `fastlane`. 

This action only suppresses the tests...well, it has been augmented a little to also provide you a list of the tests that are to be skipped and those that are not _from the xml report_.

**Comment by lyndsey-ferguson** [comment]
Thinking about this more, the intent of this action is to react to a test run for a secondary run.

**Comment by lyndsey-ferguson** [comment]
Closing the issue as this is too out of my planned area of responsibility for this plugin.

**Comment by lyndsey-ferguson** [comment]
@ericwengelking @WesleyJacobsMP you should checkout the `multi_scan` action in my new fastlane plugin, `test_center`. This pretty much will replace `setup_fragile_tests_for_rescan` and give you what you're looking for.

**Comment by ericwengelking** [comment]
I actually found a way to accomplish what I needed with this plugin.  First before running my tests I do a `build_without_testing` then when running my tests I can pass `test_without_build` and it works fine.  @lyndsey-ferguson where can I look into your new plugin?  I'd be interested to see what it offers and if I can contribute back.

**Comment by lyndsey-ferguson** [comment]
[Here](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center) is the new plugin. It is a work in progress, but every action in the plugin, including `multi_scan` is fully functional and under unit tests. You can add the plugin via `fastlane add test_control` and then start using it. You can use your existing `scan` options with `multi_scan` as long as you pass in `try_count`. See the [available_options](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/blob/master/lib/fastlane/plugin/test_center/actions/multi_scan.rb#L87)

**Comment by WesleyJacobsMP** [comment]
@ericwengelking Can you provide me with your fastfile to check how you set it up? Thanks in advance

**Comment by lyndsey-ferguson** [comment]
By the way, the new plugin with the multi-scan action does the build without testing and the test without building automatically.

**Comment by WesleyJacobsMP** [comment]
As fas as I can tell, the new plugin does not support xcworkspaces. Which is what I need

**Comment by lyndsey-ferguson** [comment]
The `multi_scan` action supports all the options of `scan` action plus how many times you want to retry tests. `scan` supports [workspaces](https://github.com/fastlane/fastlane/blob/master/scan/lib/scan/options.rb#L15). If you're referring to the other actions in the plugin, you're right, that's on my list of things to attend to.

**Comment by WesleyJacobsMP** [comment]
I was using the wrong argument in my options, my bad. Cause it asked for a project I used that, which does not accept a workspace file
