### ISSUE TITLE
custom_report_file_name is deprecated

### ISSUE THREAD

**Issue by WesleyJacobsMP** [lyndsey-ferguson/setup_fragile_tests_for_rescan#5]
I'm getting the following error when trying to use the plugin with the example fastfile:
"failure noted: Using a :custom_report_file_name with multiple :output_types (html,junit) will lead to unexpected results. Use :output_files instead."

I haven't been able to fix it using output_files, since it does not support xml output_types.
Do you know how to fix this?

**Comment by lyndsey-ferguson** [comment]
You should either specify one output type, 'junit' or give a comma separated list for ':output_files'.
